'use client';

import { useState, useRef, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { Send, Loader2, Sparkles, GraduationCap, Stethoscope, Brain, MessageSquare, Star } from 'lucide-react';
import Link from 'next/link';

interface Message {
  id: string;
  role: 'user' | 'assistant' | 'expert';
  content: string;
  timestamp: Date;
  expertName?: string;
  expertRating?: number;
}

interface Expert {
  id: string;
  name: string;
  specialty: string;
  rating: number;
  reviews: number;
  price: number;
  available: boolean;
  avatar?: string;
}

const EXPERTS: Expert[] = [
  {
    id: '1',
    name: 'Dr. Sarah Chen',
    specialty: 'Geriatric Care',
    rating: 4.9,
    reviews: 127,
    price: 49,
    available: true,
  },
  {
    id: '2',
    name: 'Nurse James Wilson',
    specialty: 'Medication Management',
    rating: 4.8,
    reviews: 89,
    price: 35,
    available: true,
  },
  {
    id: '3',
    name: 'Dr. Maria Rodriguez',
    specialty: 'Chronic Disease Management',
    rating: 4.9,
    reviews: 203,
    price: 59,
    available: false,
  },
  {
    id: '4',
    name: 'Care Coordinator Lisa Park',
    specialty: 'Family Care Planning',
    rating: 4.7,
    reviews: 156,
    price: 29,
    available: true,
  },
];

export default function HelperEnginePage() {
  const { data: session, status } = useSession();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      role: 'assistant',
      content: "Hi! I'm CareOS HelperEngine. Ask me anything - I can help with questions, connect you with verified vendors, or search available leads and opportunities. What do you need?",
      timestamp: new Date(),
    },
  ]);
  const [input, setInput] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [showExperts, setShowExperts] = useState(false);
  const [selectedExpert, setSelectedExpert] = useState<Expert | null>(null);
  const [showLeads, setShowLeads] = useState(false);
  const [leads, setLeads] = useState<any[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || isProcessing) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input.trim(),
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setIsProcessing(true);

    // Simulate AI response
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // Check if question might need vendor/expert help
    const needsVendor = /(consult|expert|vendor|service|help me|need|looking for|find|search)/i.test(input);
    const isLeadSearch = /(search|find|leads|opportunities|available)/i.test(input);

    if (isLeadSearch) {
      // Search for leads
      try {
        const response = await fetch(`/api/helper-engine/leads?q=${encodeURIComponent(input)}`);
        const data = await response.json();
        if (data.success && data.leads.length > 0) {
          setLeads(data.leads);
          setShowLeads(true);
          const assistantMessage: Message = {
            id: (Date.now() + 1).toString(),
            role: 'assistant',
            content: `I found ${data.leads.length} matching lead${data.leads.length > 1 ? 's' : ''}. Check the leads panel on the right to see details and connect with vendors.`,
            timestamp: new Date(),
          };
          setMessages((prev) => [...prev, assistantMessage]);
        } else {
          const assistantMessage: Message = {
            id: (Date.now() + 1).toString(),
            role: 'assistant',
            content: "I couldn't find any matching leads. Try searching with different keywords or ask me a question directly.",
            timestamp: new Date(),
          };
          setMessages((prev) => [...prev, assistantMessage]);
        }
      } catch (error) {
        console.error('Error searching leads:', error);
      }
    } else if (needsVendor && !selectedExpert) {
      setShowExperts(true);
      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: "I can help with general questions, but for personalized help, I'd recommend connecting with one of our verified vendors. Would you like to see available vendors?",
        timestamp: new Date(),
      };
      setMessages((prev) => [...prev, assistantMessage]);
    } else {
      // AI response
      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: `I understand you're asking about: "${input}". Here's what I can tell you:\n\n[AI Response - This would be generated by Claude API in production]\n\nYou can also search for leads or connect with vendors for more help.`,
        timestamp: new Date(),
      };
      setMessages((prev) => [...prev, assistantMessage]);
    }

    setIsProcessing(false);
  };

  const handleConnectExpert = (expert: Expert) => {
    setSelectedExpert(expert);
    setShowExperts(false);
    
    const expertMessage: Message = {
      id: Date.now().toString(),
      role: 'expert',
      content: `Hi! I'm ${expert.name}, ${expert.specialty} specialist. How can I help you today?`,
      timestamp: new Date(),
      expertName: expert.name,
      expertRating: expert.rating,
    };

    setMessages((prev) => [...prev, expertMessage]);
  };

  if (status === 'loading') {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="animate-spin h-8 w-8 text-blue-600" />
      </div>
    );
  }

  if (status === 'unauthenticated') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-4 text-gray-900 dark:text-white">
            Please sign in
          </h1>
          <Link
            href="/auth/signin"
            className="text-blue-600 dark:text-blue-400 hover:underline"
          >
            Sign In
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-violet-50 to-purple-100 dark:from-gray-900 dark:to-gray-800">
      <div className="container mx-auto px-4 py-8 max-w-6xl">
        {/* Header */}
        <div className="mb-6">
          <Link
            href="/careos-unified"
            className="text-blue-600 dark:text-blue-400 hover:underline mb-4 inline-block"
          >
            ← Back to CareOS
          </Link>
          <div className="flex items-center gap-3 mb-2">
            <Sparkles className="text-violet-600 dark:text-violet-400" size={32} />
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
              HelperEngine
            </h1>
          </div>
          <p className="text-gray-600 dark:text-gray-400">
            Ask anything, search leads, and connect with verified vendors
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Chat Interface */}
          <div className="lg:col-span-2">
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg overflow-hidden flex flex-col h-[600px]">
              {/* Messages */}
              <div className="flex-1 overflow-y-auto p-6 space-y-4">
                {messages.map((message) => (
                  <div
                    key={message.id}
                    className={`flex ${
                      message.role === 'user' ? 'justify-end' : 'justify-start'
                    }`}
                  >
                    <div
                      className={`max-w-[80%] rounded-2xl px-4 py-3 ${
                        message.role === 'user'
                          ? 'bg-violet-600 text-white'
                          : message.role === 'expert'
                          ? 'bg-green-100 dark:bg-green-900 text-gray-900 dark:text-white border-2 border-green-300 dark:border-green-700'
                          : 'bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-white'
                      }`}
                    >
                      {message.role === 'expert' && message.expertName && (
                        <div className="flex items-center gap-2 mb-2 pb-2 border-b border-green-300 dark:border-green-700">
                          <GraduationCap size={16} className="text-green-600 dark:text-green-400" />
                          <span className="font-semibold text-sm">{message.expertName}</span>
                          {message.expertRating && (
                            <div className="flex items-center gap-1">
                              <Star size={12} className="text-yellow-500 fill-yellow-500" />
                              <span className="text-xs">{message.expertRating}</span>
                            </div>
                          )}
                        </div>
                      )}
                      <p className="text-sm whitespace-pre-wrap">{message.content}</p>
                      <p className="text-xs opacity-70 mt-2">
                        {message.timestamp.toLocaleTimeString([], {
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </p>
                    </div>
                  </div>
                ))}
                {isProcessing && (
                  <div className="flex justify-start">
                    <div className="bg-gray-100 dark:bg-gray-700 rounded-2xl px-4 py-3">
                      <Loader2 className="animate-spin h-4 w-4 text-gray-400" />
                    </div>
                  </div>
                )}
                <div ref={messagesEndRef} />
              </div>

              {/* Input */}
              <div className="border-t border-gray-200 dark:border-gray-700 p-4 bg-white dark:bg-gray-800">
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && handleSend()}
                    placeholder="Ask a question or describe your care situation..."
                    className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-xl bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-violet-500"
                    disabled={isProcessing}
                  />
                  <button
                    onClick={handleSend}
                    disabled={!input.trim() || isProcessing}
                    className="bg-violet-600 hover:bg-violet-700 disabled:bg-gray-300 disabled:cursor-not-allowed text-white rounded-xl px-6 py-2 flex items-center gap-2 transition-colors"
                  >
                    <Send size={18} />
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Sidebar - Experts & Leads */}
          <div className="space-y-6">
            {/* Leads Search */}
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-6">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                <MessageSquare className="text-violet-600 dark:text-violet-400" size={24} />
                Search Leads
              </h2>
              <div className="mb-4">
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onKeyPress={async (e) => {
                    if (e.key === 'Enter' && searchQuery.trim()) {
                      try {
                        const response = await fetch(`/api/helper-engine/leads?q=${encodeURIComponent(searchQuery)}`);
                        const data = await response.json();
                        if (data.success) {
                          setLeads(data.leads || []);
                          setShowLeads(true);
                        }
                      } catch (error) {
                        console.error('Error searching leads:', error);
                      }
                    }
                  }}
                  placeholder="Search available leads..."
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-violet-500"
                />
              </div>
              {showLeads && leads.length > 0 && (
                <div className="space-y-3 max-h-96 overflow-y-auto">
                  {leads.map((lead) => (
                    <div
                      key={lead.id}
                      className="border border-gray-200 dark:border-gray-700 rounded-lg p-3 hover:border-violet-300 dark:hover:border-violet-600 transition-colors"
                    >
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex-1">
                          <h3 className="font-semibold text-sm text-gray-900 dark:text-white">
                            {lead.category.replace('_', ' ')}
                          </h3>
                          <p className="text-xs text-gray-600 dark:text-gray-400 mt-1 line-clamp-2">
                            {lead.needDescription}
                          </p>
                        </div>
                        {lead.leadValue && (
                          <span className="text-xs font-semibold text-green-600 dark:text-green-400 ml-2">
                            ${lead.leadValue}
                          </span>
                        )}
                      </div>
                      <div className="flex items-center justify-between mt-2">
                        <span className="text-xs text-gray-500 dark:text-gray-400">
                          {lead.locationState || 'Anywhere'}
                        </span>
                        <span
                          className={`text-xs px-2 py-1 rounded-full ${
                            lead.status === 'consented'
                              ? 'bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200'
                              : 'bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-200'
                          }`}
                        >
                          {lead.status}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Experts Sidebar */}
            {/* Available Vendors */}
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-6">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                <GraduationCap className="text-violet-600 dark:text-violet-400" size={24} />
                Verified Vendors
              </h2>
              <div className="space-y-3">
                {EXPERTS.filter((e) => e.available).map((expert) => (
                  <div
                    key={expert.id}
                    className="border border-gray-200 dark:border-gray-700 rounded-xl p-4 hover:border-violet-300 dark:hover:border-violet-600 transition-colors cursor-pointer"
                    onClick={() => handleConnectExpert(expert)}
                  >
                    <div className="flex items-start justify-between mb-2">
                      <div>
                        <h3 className="font-semibold text-gray-900 dark:text-white">
                          {expert.name}
                        </h3>
                        <p className="text-sm text-gray-600 dark:text-gray-400">
                          {expert.specialty}
                        </p>
                      </div>
                      <div className="flex items-center gap-1">
                        <Star size={14} className="text-yellow-500 fill-yellow-500" />
                        <span className="text-sm font-medium">{expert.rating}</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between mt-2">
                      <span className="text-xs text-gray-500 dark:text-gray-400">
                        {expert.reviews} reviews
                      </span>
                      <span className="text-sm font-semibold text-violet-600 dark:text-violet-400">
                        ${expert.price}/session
                      </span>
                    </div>
                    <div className="mt-2">
                      <span className="inline-block px-2 py-1 bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300 text-xs rounded-full">
                        Available now
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Info Card */}
            <div className="bg-gradient-to-br from-violet-500 to-purple-600 rounded-2xl p-6 text-white">
              <h3 className="font-semibold mb-2">Vendor Connect</h3>
              <p className="text-sm opacity-90 mb-4">
                Connect with verified vendors for any service or need. Search leads, accept opportunities, and schedule meetings.
              </p>
              <ul className="text-sm space-y-1 opacity-90">
                <li>✓ Verified vendors</li>
                <li>✓ Lead marketplace</li>
                <li>✓ Calendar integration</li>
                <li>✓ Secure scheduling</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

